### ISSUE TITLE
[Proposal] Make the sklearn dependency soft / optional

### ISSUE THREAD

**Issue by ejhumphrey** [pescadores/pescador#21]
The guts of pescador are pure python (fishsnake), with two exceptions:
- pyzmq for background threading
- sklearn for BaseEstimator inheritance

The former is kind of core to what pescador is, whereas the second is just for maintaining a common interface with another library (which you could very well never touch). Worth noting, sklearn, and thus scipy, are bloating this build on travis, and any project that touches pescador. 

Granted there's a decent chance that anyone using pescador is probably going to be using one or both of those libs, but it's kinda bumming me out that pescador build / install times are almost double digit minutes, while the tests themselves take seconds.

discuss.

**Comment by bmcfee** [comment]
Yeah, that's reasonable, but it will take some api breakage to do it properly.  (Moving StreamLearner into its own submodule.)

**Comment by ejhumphrey** [comment]
What's the timeline for v0.2?

**Comment by bmcfee** [comment]
None as of yet, since I haven't seen much need for major revision until now.

**Comment by bmcfee** [comment]
Because I'm a lazy individual, #23 also implements a modification to the travis configs that should bring the build time back down to manageable.

**Comment by bmcfee** [comment]
Alternately: how do you feel about just dropping the streamlearner object?  I don't think it gets used much (ever?) and dklearn does a reasonable enough job of this sort of thing anyway for people that just want out-of-core learning.

**Comment by cjacoby** [comment]
I have a new repo of basically "pescador tools" that I could wrap it into. It might make sense there. Otherwise, I think it's probably fine to drop it.

https://github.com/cjacoby/streambuilder
It's only a few days old, and I'm still in the middle of setting up a bunch of things, but you should get the idea. (The current readme is a tad out of date, but at least explains what I'm getting at.) I found myself building this thing at least twice, so I decided to make a repo of it.
