### ISSUE TITLE
Mux a Mux stream

### ISSUE THREAD

**Issue by faroit** [pescadores/pescador#79]
For non obvious reasons I would like to multiplex a stream with an already multiplexed stream. 

```python
import pescador

def data_high():
    while True:
        yield dict(X=1)


def data_low():
    while True:
        yield dict(X=0)


def data_neg():
    while True:
        yield dict(X=-1)


high_stream = pescador.Streamer(data_high)
low_stream = pescador.Streamer(data_low)

mux_low_high = pescador.mux.Mux(
    [low_stream, high_stream], 2
)

mux_mux_neg = pescador.mux.Mux(
    [data_neg, mux_low_high], 2,
)

print([X for X in mux_mux_neg.generate(max_batches=10)])
```

Generating samples from `mux_mux_neg` results in an error:

```
Traceback (most recent call last):
  File "keras_example.py", line 130, in <module>
    print([X for X in mux_mux_neg.generate(max_batches=10)])
  File ".env/lib/python2.7/site-packages/pescador/mux.py", line 157, in generate
    with core.StreamActivator(self):
  File ".env/lib/python2.7/site-packages/pescador/core.py", line 14, in __enter__
    self.streamer.activate()
  File ".env/lib/python2.7/site-packages/pescador/mux.py", line 145, in activate
    self.__new_seed(self.stream_idxs_[idx]))
  File ".env/lib/python2.7/site-packages/pescador/mux.py", line 247, in __new_seed
    return (self.seed_pool[idx].generate(max_batches=n_stream),
AttributeError: 'function' object has no attribute 'generate'
```

Even though workarounds are simple and I can't think of any justfied applications where this would be more practical than just muxing the 3 streams, I just wonder if this is intended?

**Comment by bmcfee** [comment]
The problem here is that `Mux` only accepts streamers, not arbitrary iterators.

If you replace `data_neg` with `pescador.Streamer(data_neg)`, it ought to work.

We should definitely have some type checking inside `Mux` to catch this kind of thing though.

**Comment by bmcfee** [comment]
Side note: I know @ejhumphrey has been actively hacking away at making this whole process less cumbersome, he might have some insight to share on how this might change in the future.

**Comment by ejhumphrey** [comment]
@bmcfee's [first comment](https://github.com/pescadores/pescador/issues/79#issuecomment-292788586) is on point, both in (a) what would make it work and (b) that someone should enforce the streamer interface. I currently have changes [on a branch](https://github.com/pescadores/pescador/blob/ejh_20170403_test_refactor/pescador/core.py#L11) that implements this, so ... how bout that.

As for looming API changes, two things to keep in mind:
- `max_batches` is going to change to `max_iter`; I would also like to `s/generate/iterate`, but I anticipate more debate around that. 
- In the near future, `Mux` will take any iterable type. @faroit your initial code would still fail (since a generator function is not an iterable), but I *think* that instantiating the generator *would*, e.g. `mux_mux_neg = pescador.mux.Mux([data_neg(), mux_low_high], 2,)`. No promises though.

**Comment by bmcfee** [comment]
> max_batches is going to change to max_iter; I would also like to s/generate/iterate, but I anticipate more debate around that.

Getting off-topic here, but we'll do this via deprecation renames, so you'll get warnings but things won't break.

**Comment by ejhumphrey** [comment]
ya, i've got a PR coming post-haste ... and I expect I'll have to change most of it to handle the deprecation stuff "correctly" 🙁

**Comment by bmcfee** [comment]
@ejhumphrey [futurepast](https://github.com/amueller/futurepast) might be useful here

**Comment by ejhumphrey** [comment]
well now that we're in Full-on Tangent, I'd like to get this PR out for comments, and then do The Right Thing while we debate the proposed semantics.

**Comment by faroit** [comment]
> The problem here is that Mux only accepts streamers, not arbitrary iterators.

yeah, right so this has actually nothing to do with the mentioned problem. 

> We should definitely have some type checking inside Mux to catch this kind of thing though

that would make sense, yes. But feel free to close this issue.

@ejhumphrey 
> max_batches is going to change to max_iter

👍 for this. max_batches is very confusing except for the `BufferedStreamer`

Thanks!
