### ISSUE TITLE
ZMQStreamer needs kill signal

### ISSUE THREAD

**Issue by ejhumphrey** [pescadores/pescador#82]
Under some scenarios, ZMQStreamers are left hanging (KeyboardInterrupt, Keras' epochs, etc). We'll need some machinery to kill the backgrounded process to not block execution.

**Comment by cjacoby** [comment]
Do you have a solution in mind? Some underbaked thoughts from googling a bit:

* Explicitly catch errors in the receiver, close the context, and then re-raise?
    * http://zguide.zeromq.org/py:interrupt

* Use a poller to unblock the receiver?
    * (http://stackoverflow.com/questions/17174001/stop-pyzmq-receiver-by-keyboardinterrupt)

* Or, maybe provide a `signal` callback or list of possible exceptions to ZMQStreamer?
   * (same S.O. as previous, but the runner up responses)

**Comment by bmcfee** [comment]
I think we actually have this already in the [`finally`](https://github.com/pescadores/pescador/blob/master/pescador/zmq_stream.py#L199-L204) clause of the ZMQStreamer.  But for whatever reason, it doesn't work properly.  I'll investigate.

**Comment by bmcfee** [comment]
Confirmed: ZMQStreamer is behaving correctly, it's just that the example that caused hanging was not using the `timeout` parameter.

We should set a non-zero default `timeout` going forward.  Since this only affects the waiting time on cleanup at the end of streaming, it shouldn't affect the sequence of data produced by the streamer, and therefore doesn't violate backwards compatibility.
