### ISSUE TITLE
On Muxes

### ISSUE THREAD

**Issue by ejhumphrey** [pescadores/pescador#84]
Recent adventures in pescador development have resulted in some observations / questions about Muxes, their (desired) behavior.

Firstly, the sampling nature of a Mux can be put in three modes, controlled through two binary parameters (resulting in one "indifferent" state):
- `with_replacement=False`, `revive=False`: Run every stream once to exhaustion.
- `with_replacement=False`, `revive=True`: Run every stream indefinitely; there is no duplication at the level of active streams, but source streams are reused.
- `with_replacement=True`, `revive=*`: Streams are sampled independently and indefinitely; a single stream may be active multiple times.

From discussions with @cjacoby, there are some other use cases in which one would want to multiplex streams, but can't be achieved with this interface. To kick off the discussion, here are some that I'd like:

**Permuted Mux:** Streams are activated as a permutation of the input ordering, e.g. for n_streams=3, the activation ordering could be `stream_idx=[0, 2, 1, 2, 0, 1, 1, 2, 0, ...]`. 

**RoundRobin Mux:** Streams are deterministically multiplexed in the order provided, e.g. `stream_idx=[0, 1, 2, 0, 1, 2, ...]`.

What's interesting is that Permuted and RoundRobin Mux are pretty similar, and could be achieved with a shuffle parameter. In particular, I'm curious what other kinds of common behavior could be factored, which might lead to something like:

```
class BaseMux(Streamer):
    ...

class ShuffledMux(BaseMux):
    ...

class SampledMux(BaseMux):
    ...
```

...where `SampledMux` is actually the (Stochastic)`Mux` of today.

Thoughts? Others?

**Comment by cjacoby** [comment]
Thought: A Mux in the abstract:

A `Streamer` which consumes/contains a list of streamers, and produces one sample from one of them at every step.

Components/methods of every streamer (which could be unit tested!):
 * a method for choosing the “active” streams.
 * a method for choosing a sample from the active streams
 * Handling streams that die.
 * ?

**Comment by cjacoby** [comment]
# Mux Use Cases
(which we need to cover)

* I want to sample from N streams equally (Permuted/Shuffled Mux?)

* I want to sample from N streams, weighting how often we sample each stream differently.
    - Handle class imbalance, etc.
    - A `SampledMux` with uniqueness guarantees / constraints on how sampled.

* I have a very very large dataset, and I want to be able to pull subsets from it which I can fit in memory, and sub-sample from those, keeping only one or a small number open at a time.
    - probably revive=True, with_replacement=True, rate=big, k=small

* I have a very large number of individual examples as single files/npys, and want to wrap them all in streamers, and mux them together.
    - Could be a sort of permutation; you could have revive=False, with_replacement=True, k=big, wrapped in a mux which forces you to Permute the examples
    - Could be do revive=True, with_replacement=True, k=big, ...

**Comment by bmcfee** [comment]
Synced up with @ejhumphrey just now, and strategized on this a bit.

I think the plan should be to deprecate `Mux` in favor of `PoissonMux` (inherits from `BaseMux`), and clean up the API a bunch, eg, replace `with_replacement` and `revive` independent parameters by a single parameter `mode` with semantically meaningful values like `'with_replacement', 'single_active', 'exhaustive'`.  (Or better names, iono.)

This can be done for 1.1, with the current `Mux` removed in 2.0.

We can punt on implementing other muxes until 2.0.

Sound reasonable?

**Comment by bmcfee** [comment]
Side note: we might want to dig into the [itertools](https://docs.python.org/3.6/library/itertools.html#itertools.tee) for potential mux strategies, eg, chain, round-robin, filter, takewhile/filterfalse, etc.

**Comment by cjacoby** [comment]
👍 I like this plan a lot.  If we could come up with a solid plan for what should happen, I'd be happy to take a pass at implementing it.

**Comment by cjacoby** [comment]
Hey folks; I've been working on this, and am finally making some progress. As it turns out, it takes a significant amount of time in each sitting to get one's brain wrapped around all of this enough to make any progress (I know @ejhumphrey has also experienced this), so while I have looked at it a bunch of times over the past month or so, I feel like I only made any progress understanding what is going on tonight.

So, after working carefully through all of the code and the Mux options (`with_replacement`, `revive`, `prune_empty_streams`) and looking at `itertools` and the above thoughts, I have come up with the following approximate proposal. 

Embedded below are several questions / clarifications that I'd appreciate answers for so I can move forward.

## 1. `BaseMux` is an "Interface" which defines the required interface for a Mux.

What is a Mux? (and therefore what `BaseMux` provides)

A `Mux` is at its simplest a Streamer which wraps N other streamers,
and at every step yields a sample from one of its sub-streamers.

The BaseMux must have the following functions to fulfill these requirements:

`__init__(self, streamers, random_state=None)`
`iterate(self, max_iter=None)` (from Streamer)
`activate()` (from Streamer)
`deactivate()` (from Streamer)
`_next_stream_index()` - chooses what stream to yield from at each step.

##  2. BaseMux Subclasses

### a. `PoissonMux`

Essentially identical to the previous `Mux`. `PoissonMux` *ideally* should have
a single `mode` parameter which selects how it operates, instead of 2-3 parameters
which generally seem to increase the opacity and not help very much with understanding what's
going on.

Terminology for clarification:
`pool streams`: Eric calls these "source streams" above. They are the pool of available streams to choose from, given when the object is instantiated.
`active streams`: the `k` streams chosen to be active

Looking over the functionality more carefully, I believe that these are the fundamental modes of operation, which are currently confusingly mixed into `with_replacement`, `revive`, and `prune_empty_streams`.

* Prune streams when they die, or revive them

* Unique selection of streams (a "pool streamer" can be chosen at most once) vs non-unique (pool-streamers can be chosen any number of times (up to `k`)). Currently this is being achieved by temporarily setting the `distribution_` for this streamer to 0 while it is in use, and I believe that is what is causing seemingly necessary complication with `with_replacement` and `revive`, where as we could come up with a simpler way to do it and not need all that cruft.

Therefore, I propose having only two parameters:
* `revive` = [True/False] (alternatively `on_exhaustion`=["revive" / "prune"] or something like that)
* `unique_streams` = [True/False]

### b. `ShuffledMux`
    
k = N streamers; draws one sample from each stream, guaranteeing to choose them with equal probability. Should also have `revive=True/False` or `revive/prune`.

(This is actually a `PoissonMux(k=N, unique_streams=True)`)

### c. `RoundRobinMux`

Similar to `ShuffledMux` but guaranteed to iterate over the streamers in strict order. Should also have a revive / prune setting.

This would be a `PoissonMux(k=N, unique_streams=True)` without shuffling / random selection of the indeces. (In practice I would probably override a `_next_stream_index()` to do this.


### d. `ChainMux`

    As in itertools.chain(). Runs the first streamer to exhaustion, then the second, then the third, etc. k=1 Streamers.

## 3. Old Mux still works but is deprecated


## Misc Observations
    * How should prune_empty_streams work? Currently, none of the intermediate checks also check anything against valid_streams_, making it potentially dangerous / ineffective in the `(revive && 
not with_replacement)` configuration. Something here looks fishy and I though I would mention it. But this shouldn't be a problem under the refactor I'm proposing.


With a go-ahead from y'all, I'll move forward on this tomorrow.

**Comment by bmcfee** [comment]
Whoo, tis a doozy here, but thanks for collecting thoughts on this!  I'll respond inline:



> iterate(self, max_iter=None) (from Streamer)
> activate() (from Streamer)
> deactivate() (from Streamer)
> _next_stream_index() - chooses what stream to yield from at each step.

It seems like `_next_stream_index()` needs to be stateful.  Should it be a generator?  Or a method that interfaces with the mux's internal state to determine the next index?



> Therefore, I propose having only two parameters:
> 
> revive = [True/False] (alternatively on_exhaustion=["revive" / "prune"] or something like that)
> unique_streams = [True/False]

`unique_streams` seems like a rename of "with replacement", which is standard statistical terminology for this kind of sampling.  I'm not sure I see the need for a change here.

The `prune_empty` vs `revive` situation is tricky.  They're superficially the same idea, but it all comes down to preventing infinite loops.  There's a difference between a streamer being exhausted but able to generate new data if restarted, and a streamer that can never produce new data.  In the latter case, you can get stuck in an infinite loop when it's the only available remaining streamer.

I think it's fair to always force `prune_empty=True` so that detected empty streams are never considered again, but I also think this needs to be a flag that the user can control.



> (This [ShuffledMux] is actually a PoissonMux(k=N, unique_streams=True))

The `rate` parameter needs to be set so that the streams are never prematurely terminated.  Same goes for `RoundRobin` and `ChainMux`.  I think it's probably simpler to implement these separately without relying on poissonmux?

**Comment by cjacoby** [comment]
> _next_stream_index() - chooses what stream to yield from at each step.
> It seems like _next_stream_index() needs to be stateful. Should it be a generator? Or a method that interfaces with the mux's internal state to determine the next index?

In the `PoissonMux` case, I imagine it'd just be something like:

```python
def _next_stream_index(self):
    return self.rng.choice(self.k, p=(self.stream_weights_ /
                                      self.weight_norm_))
```
This is exactly the line that choses the next stream index currently, except how this works in other Muxes is different, so we just need to be able to abstract it. For `ShuffledMux`, it is still the same, only k == self.n_streamers, however for `RoundRobinMux`, it probably needs to have state and be something like:

```python
def _next_stream_index(self):
    next_index = self.current_index
    self.current_index = self.current_index + 1
    if self.current_index >= self.n_streams:
        self.current_index = 0
    return next_index
```

> unique_streams seems like a rename of "with replacement", which is standard statistical terminology for this kind of sampling. I'm not sure I see the need for a change here.

Ah now that I've stepped back and you point that out I see it and it makes more sense to me.

> The prune_empty vs revive situation is tricky. They're superficially the same idea, but it all comes down to preventing infinite loops. There's a difference between a streamer being exhausted but able to generate new data if restarted, and a streamer that can never produce new data. In the latter case, you can get stuck in an infinite loop when it's the only available remaining streamer.

> I think it's fair to always force prune_empty=True so that detected empty streams are never considered again, but I also think this needs to be a flag that the user can control.

So given this, I think I'm back to (this is the same as you said before, I think):

* one `mode` parameter, in ['with_replacement', 'single_active', 'exhaustive']
* Also a `prune_empty_streams` parameter which defaults to True. 

>> (This [ShuffledMux] is actually a PoissonMux(k=N, unique_streams=True))
> The rate parameter needs to be set so that the streams are never prematurely terminated. Same goes for RoundRobin and ChainMux. I think it's probably simpler to implement these separately without relying on poissonmux?

Yes, I agree. I was just thinking out loud and I didn't edit that part out.

Okay! I'm gonna try for a PR on this by the end of this week, while I still have the mental model of it all working.

**Comment by bmcfee** [comment]
> In the PoissonMux case, I imagine it'd just be something like:

:+1: I just wanted to be 100% clear on this one, but I like this design.

I'd say that `ShuffledMux` still has state contained in `self.rng`, which we need for reproducibility.  I think in general all muxen are best interpreted as state machines.



> Ah now that I've stepped back and you point that out I see it and it makes more sense to me.

:+1: 

> one mode parameter, in ['with_replacement', 'single_active', 'exhaustive']

I like this.  The problem was always that we only have 3 distinct configurations, which were encoded as 2 indpendent flags.  I'm all for coding these as enumerated values instead, as long as they're clearly defined and documented to the user.



> Also a prune_empty_streams parameter which defaults to True.

:+1: 



> Okay! I'm gonna try for a PR on this by the end of this week, while I still have the mental model of it all working.

:100: ** :100:

**Comment by bmcfee** [comment]
#103 resolves all of the issues here
